### ISSUE TITLE
Repo with development history preserved

### ISSUE THREAD

**Issue by FabioLolix** [sebaro/Yarock#2]
Hello @sebaro, thanks for continuing to develop yarock!

I would like that it have development history preserved so I made repo converted from launchpad 

https://github.com/FabioLolix/yarock

following this guide https://jugmac00.github.io/blog/migrate-a-repository-from-bazaar-to-git/

I could transfer it to you and you can rebase your commits to this

btw there is the `CRLF/LF`  thing o every file

```
warning: in the working copy of 'CMakeLists.txt', CRLF will be replaced by LF the next time Git touches it
```

I'm maintaining the AUR pkgbuild of yarock-mpv and could work also on pkgbuilds of your fork

**Comment by sebaro** [comment]
You mean to create branches for each release or just to have all commits from Launchpad added to this repo?

The code is from Launchpad (downloaded archive) so it has the windows characters, only the files I changed don't have them.

**Comment by FabioLolix** [comment]
This have slipped sorry

> You mean to create branches for each release or just to have all commits from Launchpad added to this repo?

Neither; transfering my repo or use `Import repository` here from github is fastest and safer

Your development have been only 5 commit so it is easy to start again, are you familiar with `git log`, `git chekcout`, `git format-patch` and `git apply` ?

**Comment by sebaro** [comment]
Is it possible to pull your repo onto a new branch (base) and rebase the main branch to base branch?

Edit:
I have created the "base" branch pulled from you repository, now "main" branch is based on "base" and includes my commits.

**Comment by FabioLolix** [comment]
> Is it possible to pull your repo onto a new branch (base) and rebase the main branch to base branch?

I don't know how to do that but I've seen you have make it

Thanks for caring :)

> The code is from Launchpad (downloaded archive) so it has the windows characters, only the files I changed don't have them.

I remembered there is `dos2unix`, likely is possible to run it to the whole repo

and last request from me, can you delete and remake the "github release"? (the git tag instead is fine)

**Comment by sebaro** [comment]
> and last request from me, can you delete and remake the "github release"? (the git tag instead is fine)

After I remove the CR characters?

**Comment by FabioLolix** [comment]
> After I remove the CR characters?

Don't make difference
